### ISSUE TITLE
[FEATURE] Upgrade to NODE 20

### ISSUE THREAD

**Issue by lcoelho-wyn** [redhat-actions/buildah-build#132]
### Is your feature request related to a problem? Please describe.

GitHub actions now warn you when any action used on your workflow is running on a deprecated version of NODE. See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ for more information.

### Describe the solution you'd like

The action being ported to use NODE 20.

### Describe alternatives you've considered

No alternatives. will keep using until it is ported or GitHub stops it from working

### Additional context

N/A

**Comment by lcoelho-wyn** [comment]
there is already a PR for this: https://github.com/redhat-actions/buildah-build/pull/128

**Comment by divyansh42** [comment]
Fix has been released with version v2.13
