### ISSUE TITLE
Add 'digest' output

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/buildah-build#32]
Like we have in push-to-registry, it would be useful to have an output that contains the built image's digest.

**Comment by tetchel** [comment]
Cancelling this because it would not work the way I thought it would.

**Comment by tunedal** [comment]
@tetchel Could you elaborate on how this wouldn't work the way you thought it would? I also think I want this feature, so I would like to know if I've misunderstood how this works and, if so, what I should be doing instead.

If you potentially have multiple builds running concurrently, how do you retrieve the image built by the current job? You could work around it by tagging it with a UUID, I guess, but then just using the digest seems much simpler. Or the image ID as output would also work, which I think is what `docker build --iidfile` provides.
