### ISSUE TITLE
Add message to v1 that users should update to v2

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/buildah-build#38]
I think info level is best, at the top of the workflow. Warning level is too annoying.

Do the same for push-to-registry

**Comment by tetchel** [comment]
:warning: redhat-actions/buildah-build@v2 is now available. https://changelog-url

**Comment by tetchel** [comment]
Don't do this until the starter workflow is updated.

**Comment by Divyansh42** [comment]
Done in https://github.com/redhat-actions/buildah-build/commit/dc9713a0c9fd2f6cbad37fc78e8a64b17edb8a2e for `buildah-build` action
We won't be doing this for `push-to-registry` action as this makes `v1` version most recent one and we don't want that.
