### ISSUE TITLE
[QUESTION] How can I use a buildah script for image generation using GitHub Actions?

### ISSUE THREAD

**Issue by EvanCarroll** [redhat-actions/buildah-build#40]
### Question

https://devops.stackexchange.com/questions/13524/how-can-i-use-a-buildah-script-for-image-generation-using-github-actions

Buildah scripts typically use shell. You can see an example of a script here,

```
#!/bin/sh
ctr=$(buildah from alpine:3)
buildah commit "$ctr" myAlpineImage
```

Let's say I have such a shell script that produces an image "myAlpineImage". How can I use GitHub CI to automate the creation of this image, and preferably uploading it to GitHub Container Registry?

**Comment by Divyansh42** [comment]
If your use case is satisfied by this action, you can use this action to build image and [push-to-registry](https://github.com/redhat-actions/push-to-registry) action to push to Github Container Registry (or registry of your choice).
With this action you can also build image without dockerfile. Check [this](https://github.com/redhat-actions/buildah-build#inputs-for-build-without-dockerfile).

But, if you still want to build image typically using shell you can do something like:
```
- name: Test Build
  run: | 
    #!/bin/sh
    ctr=$(buildah from alpine:3)
    buildah commit "$ctr" my-alpine-image
```
As Github Linux runners comes with buildah pre-installed https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#installed-software

**Comment by tetchel** [comment]
closing pending any further comments
