### ISSUE TITLE
--layers option

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/buildah-build#42]
The --layers option is useful in buildah when given a persistent disk, but not useful in CI systems where the disk is discarded after each job

Since we've verified this option allows caching to work in the [self-hosted buildah runner](https://github.com/redhat-actions/openshift-actions-runner/tree/main/buildah) we should add an input for it

To keep with buildah behaviour, it should be false by default.

In addition, it may make sense to set `export BUILDAH_LAYERS=true` into the runner.

**Comment by tetchel** [comment]
I am adding BUILDAH_LAYERS=true to the buildah runner dockerfile, but if `--layers=false` is passed to this action then the env var will get overridden. 

So if `layers` is not set, do not pass `--layers` at all, to leave it up to the environment.

**Comment by Divyansh42** [comment]
Okay :+1:
