### ISSUE TITLE
Set image name 'output' on success

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/buildah-build#6]
I think it would be useful to output the image name (including tag), so it could be used by subsequent steps and would not have to be hard-coded in both steps.

**Comment by Divyansh42** [comment]
What if we output the image digest? I see tekton task use to output 'digest' in the results of the task.
Ref: https://github.com/tektoncd/catalog/blob/master/task/buildah/0.2/buildah.yaml#L54

**Comment by tetchel** [comment]
isn't the digest a hash/checksum? I was thinking more the image name:tag that could then be passed to the push-to-registry step.

**Comment by lstocchi** [comment]
Also the docker `build-push-action` returns a digest https://github.com/docker/build-push-action/blob/master/action.yml
I'm really not sure if they returns the digest or the image id (the same in the buildah task @Divyansh42 posted, the name is confusing) but my vote goes to the image id. 

It really makes no sense for me to use the output to return something that is not made up by the action. You are just returning an input that way. A user could easily create a variable and use that without hard-coding the actual value multiple times.

![image](https://user-images.githubusercontent.com/49404737/99490799-d9a9fb00-296a-11eb-9307-9e99d7aa58ea.png)

**Comment by tetchel** [comment]
in my own example, the name and tag were stored separately because they are passed to the action as separate inputs, but after the action they are one output, that's all.

**Comment by tetchel** [comment]
the full image URL is currently printed but would also be a useful output (more useful than the name)

**Comment by tetchel** [comment]
i guess somewhat related is, the image name is currently expected to include the tag, which seems counter-intuitive to me. for push-to-registry, name and tag are separate. should we split that into two inputs?

**Comment by Divyansh42** [comment]
I think splitting the input into `name` and `tag` would make a lot more sense.

**Comment by tetchel** [comment]
I added this in a65863e
