### ISSUE TITLE
[FEATURE] Consider 'manifest' support

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/buildah-build#61]
If a user wants to publish multiple images under one index, eg when building multi-arch images, the 'manifest' command is used to bundle the images together. 

https://github.com/redhat-actions/buildah-build/issues/60
https://github.com/containers/buildah/blob/main/docs/buildah-manifest.1.md
https://github.com/containers/buildah/issues/1590

**Comment by divyansh42** [comment]
This feature will be released post https://github.com/redhat-actions/buildah-build/issues/87

**Comment by divyansh42** [comment]
Manifest support is released and can be used by referencing `buildah-build@v2`.
Also to push the generated manifest, [**push-to-registry**](https://github.com/redhat-actions/push-to-registry) now supports pushing the manifest. This feature can be used by referencing `push-to-registry@v2`
