### ISSUE TITLE
Kubic packages for buildah no longer maintained

### ISSUE THREAD

**Issue by lsm5** [redhat-actions/buildah-build#93]
Hi, I was pointed to: https://github.com/redhat-actions/buildah-build/blob/5b84b381448afcee1f2e8d18d02ea76085580ca0/.github/install_latest_buildah.sh#L3 This package is no longer maintained, so I'd suggest switching to 22.04 LTS with its default buildah package instead. Also, please get rid to any other references of Kubic repos for buildah, podman and skopeo packages if any. Thanks!

**Comment by lsm5** [comment]
@divyansh42 I'm told you can install from the debian experimental repos on ubuntu 22.04 LTS. There are some others in the community setting up their own repos, though I don't think any are sufficiently usable yet.

Also, please remind me if github actions are limited to ubuntu or can you use fedora instead?

**Comment by lsm5** [comment]
@divyansh42 ack. I guess the debian experimental repo would be your best bet for now. If we come across anything more reliable, we'll publish that on the podman blog / update it in the buildah install docs.

**Comment by divyansh42** [comment]
Okay, thanks @lsm5 :slightly_smiling_face:

**Comment by lsm5** [comment]
@divyansh42 i'm working on another repo  https://build.opensuse.org/project/show/devel:kubic:libcontainers:unstable which has the latest packages for ubuntu and (hopefully) it should be a lot easier for me to maintain. Do you wanna give that a shot ?

**Comment by lsm5** [comment]
@divyansh42 to be clear, i haven't really tested this fully myself yet, so i'm looking for people to try that out and let me know if it's mature enough. I've reached out to the github actions folks too.

**Comment by divyansh42** [comment]
Sure, I will try that and let you know :)
